### ISSUE TITLE
pioreactor.local in the software installation guide

### ISSUE THREAD

**Issue by gniezen** [Pioreactor/docs.pioreactor#44]
On https://docs.pioreactor.com/user-guide/software-set-up there are a number of references to http://pioreactor.local, but step 6(i) specifically states not to use `pioreactor` as the hostname?

**Comment by CamDavidsonPilon** [comment]
a bit weird right? There's a bug somewhere internal about the hostname being `pioreactor` that I haven't dug into. However, we create a mDNS alias from `<your hostname>.local` to `pioreactor.local`. This alias is at the DNS level, so it only influences how other computers see the Pioreactor.

**Comment by CamDavidsonPilon** [comment]
That check is a safety net, but you can proceed if you want. Just comment out that line in the bash script. The script will continue and the Pioreactor will reboot. Once back up, change your config.ini `[cluster.topology]` and `[cluster.inventory]` sections to reference your new leader name, `pio1`. Probably best to do a reboot again, as well. 

----

On your phone, you should be able to still access `http://pio1.local`

**Comment by gniezen** [comment]
Thanks Cam! One last question: If I've already done an experiment on the post-Bookworm Pioreactor, will importing the data overwrite that experiment?

**Comment by CamDavidsonPilon** [comment]
Ah yes it will overwrite =( 

A solution: back-up your database with `pio run backup_database --force` and move your backed-up database at `~/.pioreactor/storage/pioreactor.sqlite.backup` elsewhere. Then perform the original import. Then "merge" the two databases together (old and new). I don't know how though - there's some stackoverflow answers, with various levels of complexity. I feel there is a risk of database corruption here, too, so please be aware of that!
